version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/PoudriereC2"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/PoudriereC2.Tests"
    schedule:
      interval: "daily"
