name: .NET tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      PostgresConnection: Host=localhost;Port=5432;Username=postgres;Database=poudrierec2;
      PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    # Required to build Azure Functions
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        dotnet-quality: 'ga'
    - name: Restore dependencies
      run: dotnet restore
    - name: Load schema
      shell: pwsh
      run: ./database/deploy.ps1 -PsqlHost localhost -SampleData
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
