name: Lint source

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install linting tools
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module PSScriptAnalyzer -ErrorAction Stop
        dotnet tool install -g dotnet-fsharplint
    - name: Restore dependencies
      run: dotnet restore
    - name: Lint with PSScriptAnalyzer
      shell: pwsh
      run: |
        Invoke-ScriptAnalyzer -Path . -Recurse -OutVariable issues
        $errors   = $issues.Where({$_.Severity -eq 'Error'})
        $warnings = $issues.Where({$_.Severity -eq 'Warning'})
        if ($errors) {
            Write-Error "There were $($errors.Count) errors and $($warnings.Count) warnings total." -ErrorAction Stop
        } else {
            Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."
        }
    - name: Lint with FSharpLint
      run: dotnet fsharplint lint ./PoudriereC2.sln